### ISSUE TITLE
What colors should I use where?

### ISSUE THREAD

**Issue by julkip** [catppuccin/hyprland#13]
The Readme only shows how to use the colors, but not what color to use in what place so that I get a nice looking theme.

**Comment by rubyowo** [comment]
up to your imagination, have a look around for some dotfiles, hell even the [Style Guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) if you want to stay true to the theme.

**Comment by LVladymyr** [comment]
Hi @julkip! Thank you for your time and this project. 
Would be happy if you provide more information about what color you use in pictures, like what section was modified in _hyprland.conf_ file, like you did in _hyprlock.conf_. I have a gap instead of imagination but really apprciate your talant and want same in my PC.
